### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by mladjan** [simonbengtsson/realmfire-swift#1]
Hi Simon,

I really like the idea of the library. I like the simplicity of the Realm database and other features of the firebase.
But when I use your models, and your library files, with my firebase plist, nothing happens. I see objects created in realm database (http://cloud.mladjan.me/3bbed4c65ef5), but no errors about sync, and nothing on firebase database. Also, inside addUpdateObject function, there is nothing: http://cloud.mladjan.me/8c8560b4bb4a

This is what I used to create a sample object to sync:

```

let realm = try! Realm()
        let obj = Dog(debug: false)
        try! realm.write {
            realm.add(obj)
            RealmFire.markForSync(obj)
            RealmFire.markForSync(obj.trainers)
            RealmFire.markForSync(obj.owner!)
            
        }
        RealmFire.sync(realm: realm)
```

**Comment by simonbengtsson** [comment]
Yes it's not functioning right now. We started using firestore + some light caching in user preferences instead of realm.

**Comment by mladjan** [comment]
Ok, so the purpose of this repo doesn't exist anymore? :D

**Comment by simonbengtsson** [comment]
Pretty much! In addition to firestore being released with better cache options than rtdb, realm has added the sync capabilities.

**Comment by mrbodich** [comment]
Hi Simon! So, Firestore can be fully used as the local database as well? I just tried do understand that but only found cache feature that is not really a local db as I see... 
Can we use Firestore for example ONLY as local db without even internet connection when the app starts for the first time?

**Comment by simonbengtsson** [comment]
Not really. You can add things to firestore offline and you can query the cache. But if you need reliable local storage its not perfect. 

For our use case we only needed reliable offline storage for a few items such as some data for the logged in user so we stored those in files and in user defaults.

**Comment by mrbodich** [comment]
Oh, I see. Can you please give me a tip how I can achieve the goal when i need offline first, that need to be synched in cloud and some data can be shared to another user?
I am just have no budget to use pure Realm with cloud feature (not even sure it has sharing).

**Comment by simonbengtsson** [comment]
I think it is worth considering if you truly need offline first or if it is better to go with firestore caching + files. But if you truly do then realm might be one option and try to sync it to firestore. You could also try more light weight alternatives such as leveldb, sqllite and coredata of course.

**Comment by mrbodich** [comment]
Thanks for the tip. I could use CoreData, no problem, but the real problem is what to choose for cloud sync then((( Did you ever try CloudKit?

**Comment by simonbengtsson** [comment]
CloudKit was out of the question for us since as far as I know you cannot share data with other users. I've not really researched other alternatives but I assume firestore is not a bad option even if you use something else for local storage.

**Comment by mrbodich** [comment]
Looks like CloudKit can share data with another users. Thanks for your answers Simon, I think I'll try to go forward with CoreData + CloudKit. Here is the info about sharing (if it can be helpful for you in future)
https://contagious.dev/blog/cloudkit-sharing-five-tips-and-tricks/

**Comment by simonbengtsson** [comment]
Interesting! Thanks for sharing.
